CREATE DATABASE API;

CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50),
    USER_PASSWORD VARCHAR(200),
    EMAIL VARCHAR(100) UNIQUE
);

CREATE TABLE MENU (
    MENU_ID INT AUTO_INCREMENT PRIMARY KEY,
    DISH_NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE CATEGORY (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE MENU_CATEGORY (
    MENU_ID INT,
    CATEGORY_ID INT,
    PRIMARY KEY (MENU_ID, CATEGORY_ID),
    FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);
